tuning:
  scheduler:
    pool-size: 2
  compensation-worker:
    scheduling-interval: ${COMPENSATION_WORKER_SCHEDULING_INTERVAL}
    pool-size: ${COMPENSATION_WORKER_POOL_SIZE}
    limit-size: ${COMPENSATION_WORKER_LIMIT_SIZE}
    retry-max: 3
  outbox-worker:
    scheduling-interval: ${OUTBOX_WORKER_SCHEDULING_INTERVAL}
    pool-size: ${OUTBOX_WORKER_POOL_SIZE}
    limit-size: ${OUTBOX_WORKER_LIMIT_SIZE}
    retry-max: 3
